export   const projects = [
    {
      id: 1,
      title: "lume",
      category: "web",
      image: "/lume.png",
      description: "A modern social media application with interactive features.",
      demoLink: "https://lume-ten.vercel.app",
      githubLink: "https://github.com/prashanttc/lume",
    },
    {
      id: 2,
      title: "Onyxclound",
      category: "web",
      image: "/onyxcloud.png",
      description: "a web based cloud storage application that allow storing files on cloud.",
      demoLink: "https://onyxcloud.vercel.app",
      githubLink: "https://github.com/prashanttc/Onyxcloud",
    },
    {
      id: 3,
      title: "doodle-ly",
      category: "web",
      image: "/doodle.png",
      description: "a web app that transform your image into animated art.",
      demoLink: "https://doodle-ly.vercel.app",
      githubLink: "https://github.com/prashanttc/doodle-ly",
    },
    {
      id: 4,
      title: "easyeats",
      category: "web",
      image: "/fooddel.png",
      description: "Fully responsive food ordering website with payment integration.",
      demoLink: "https://easyeats-0pja.onrender.com/",
      githubLink: "https://github.com/prashanttc/food-del",
    },
    {
      id: 5,
      title: "AEGIS",
      category: "web",
      image: "/citimar.png",
      description: "a anoymous complain plateform for whistleblowers.",
      demoLink: "https://example.com/demo5",
      githubLink: "https://github.com/atharva00721/citimar",
    },
    // {
    //   id: 6,
    //   title: "iOS Application",
    //   category: "app",
    //   image: "/placeholder.svg?height=300&width=400",
    //   description: "iOS app for task management and productivity.",
    //   demoLink: "https://example.com/demo6",
    //   githubLink: "https://github.com/example/project6",
    // },
  ]

  export   const technologies = [
    {
      name: "React",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
      category: "frontend",
      level: "Advanced",
    },
    {
      name: "Next.js",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
      category: "frontend",
      level: "Advanced",
    },
    {
      name: "TypeScript",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
      category: "language",
      level: "Advanced",
    },
    {
      name: "JavaScript",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
      category: "language",
      level: "Expert",
    },
    {
      name: "HTML5",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
      category: "frontend",
      level: "Expert",
    },
    {
      name: "CSS3",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
      category: "frontend",
      level: "Expert",
    },
    {
      name: "Tailwind CSS",
      icon: "/tailwindcss-original.svg",
      category: "frontend",
      level: "Advanced",
    },
    {
      name: "Node.js",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
      category: "backend",
      level: "Intermediate",
    },
    {
      name: "Express",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
      category: "backend",
      level: "Intermediate",
    },
    {
      name: "MongoDB",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
      category: "database",
      level: "Intermediate",
    },
    {
      name: "Supabase",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/supabase/supabase-original.svg",
      category: "database",
      level: "Intermediate",
    },
    {
      name: "PostgreSQL",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg",
      category: "database",
      level: "Intermediate",
    },
    {
      name: "Git",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
      category: "tool",
      level: "Advanced",
    },
    {
      name: "Figma",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg",
      category: "design",
      level: "Advanced",
    },
    {
      name: "Docker",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
      category: "devops",
      level: "Beginner",
    },
  ]